type: reference-docs
definitionId: orderManagementConfiguration
label: Order management configuration
settings:
  generateCodeSamples:
    languages:
      - lang: curl
      - lang: Java
      - lang: Python
      - lang: Node.js
      - lang: C#
  showConsole: false
  hideHostname: true
  hideDownloadButton: false
  sortPropsAlphabetically: true
  schemaDefinitionsTagName: Data definitions
  hideTryItPanel: true
  showAccessMode: true
  downloadDefinitionUrl: https://doc.toasttab.com/toast-api-specifications/toast-ordermgmt-config-api-docs.yaml

